name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # This MUST run first or git commands will fail
      - name: Checkout
        uses: actions/checkout@v4

      # Generate the snake
      - name: Generate SVG
        id: snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Risad-Raihan
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Deploy the /dist folder to output branch
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo: Risad-Raihan/Risad-Raihan
          target_branch: output
          build_dir: dist
          commit_message: "generate snake animation"
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
